// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QTfBgQPwJGHV0rrk4s0CqFHi-Gisehc',
    appId: '1:617187922510:web:e12f9c8a5be274e990e91f',
    messagingSenderId: '617187922510',
    projectId: 'gas-detekt-firebase',
    authDomain: 'gas-detekt-firebase.firebaseapp.com',
    storageBucket: 'gas-detekt-firebase.appspot.com',
    measurementId: 'G-6MY4GGLQQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD451yLv5c3K-za6Qyq5Tj3Rz1OonoSFAU',
    appId: '1:617187922510:android:4f1be0b794fe3a4890e91f',
    messagingSenderId: '617187922510',
    projectId: 'gas-detekt-firebase',
    storageBucket: 'gas-detekt-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGm5W0nHB2QNkmtIfdIq61nPXdgOJLC5g',
    appId: '1:617187922510:ios:a3814b188866f80e90e91f',
    messagingSenderId: '617187922510',
    projectId: 'gas-detekt-firebase',
    storageBucket: 'gas-detekt-firebase.appspot.com',
    iosClientId: '617187922510-ph9m7cllmmf17p1tacqafv3drctr4l9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasDetek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGm5W0nHB2QNkmtIfdIq61nPXdgOJLC5g',
    appId: '1:617187922510:ios:f1e7a8c11a96cbef90e91f',
    messagingSenderId: '617187922510',
    projectId: 'gas-detekt-firebase',
    storageBucket: 'gas-detekt-firebase.appspot.com',
    iosClientId: '617187922510-dmnq45vte4bsoq06m6224pt5l5uqfk3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gasDetek.RunnerTests',
  );
}
