name: gas_detek
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1+18

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ternav_icons: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.7+5
  vibration: ^1.7.6
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.6
  get: ^4.6.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  gallery_saver: ^2.3.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  overlay_support: ^2.1.0
  awesome_notifications: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
  - assets/images/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf


# When generate app icon, run in terminal: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_gas_detection_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_gas_detection_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon_gas_detection_app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon_gas_detection_app.png"